lib/consent_web/router.ex
defmodule ConsentWeb.Router do
  use ConsentWeb, :router

  import ConsentWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ConsentWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :fetch_cookie_consent
  end

  pipeline :static do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ConsentWeb.LayoutView, :root}
    plug :no_cookie_modal
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ConsentWeb do
    pipe_through :static

    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
    get "/cookies", PageController, :cookies
  end

  scope "/", ConsentWeb do
    pipe_through :browser

    live_session :current_user, on_mount: {ConsentWeb.UserAuth, :current_user} do
      live "/test_page", PageLive.Index, :index
    end

    get "/", PageController, :index

    get "/consent", ConsentController, :edit_summary
    post "/consent", ConsentController, :update_summary
    get "/consent/more", ConsentController, :edit_details
    post "/consent/more", ConsentController, :update_details
    get "/consent/drop_cookies", ConsentController, :drop_cookies
  end

  # Other scopes may use custom stacks.
  # scope "/api", ConsentWeb do
  #   pipe_through :api
  # end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", ConsentWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ConsentWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ConsentWeb do
    pipe_through :browser

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/consent_web/views/layout_view.ex
defmodule ConsentWeb.LayoutView do
  use ConsentWeb, :view

  import ConsentWeb.{CookieScriptComponent, ConsentComponent}

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/consent_web/templates/layout/_user_menu.html.heex
<ul>
<%= if @current_user do %>
  <li>Hi, <%= @current_user.email %></li>
  <li><%= link "Cookie Consent", to: Routes.consent_path(@conn, :edit_summary) %></li>
  <li><%= link "Learn More", to: Routes.consent_path(@conn, :edit_details) %></li>
  <li><%= link "Settings", to: Routes.user_settings_path(@conn, :edit) %></li>
  <li><%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete %></li>
<% else %>
  <li><%= link "Cookie Consent", to: Routes.consent_path(@conn, :edit_summary) %></li>
  <li><%= link "Learn More", to: Routes.consent_path(@conn, :edit_details) %></li>
  <li><%= link "Register", to: Routes.user_registration_path(@conn, :new) %></li>
  <li><%= link "Log in", to: Routes.user_session_path(@conn, :new) %></li>
<% end %>
</ul>

lib/consent_web/templates/layout/app.html.heex
<main id="main-main" role="main" class="container max-w-3xl px-4 mx-auto">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

  <%= if @show_cookie_modal do %>
  <.consent_summary show="true">
    <:header title="This site uses cookies">
    <span class="mt-4 text-sm">
      We use cookies on this site so we can provide you with personalised content,
      ads and to analyze our website's traffic.
      Check the boxes below to agree to our <a class="text-blue-600 cursor-pointer" href="/terms">Terms and Conditions</a>, and
      to allow or restrict the cookies being used.
    </span>
    </:header>
  </.consent_summary>
  <% end %>

  <%= @inner_content %>
</main>

lib/consent_web/templates/layout/live.html.heex
<main id="main-main" role="main" class="container max-w-3xl px-4 mx-auto">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= if @show_cookie_modal do %>
  <.consent_summary show="true">
    <:header title="This site uses cookies">
    <span class="mt-4 text-sm">
      We use cookies on this site so we can provide you with personalised content,
      ads and to analyze our website's traffic.
      Check the boxes below to agree to our <a class="text-blue-600 cursor-pointer" href="/terms">Terms and Conditions</a>, and
      to allow or restrict the cookies being used.
    </span>
    </:header>
  </.consent_summary>
  <% end %>

  <%= @inner_content %>
</main>

lib/consent_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <.gtag_js cookie_groups={@cookie_groups} measurement_id="G-7Z16QXERE9" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Consent", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body class="flex flex-col h-full pt-24">
    <header>
      <nav class="fixed top-0 left-0 right-0 z-30 bg-white shadow">
        <div class="container px-6 py-3 mx-auto md:flex md:justify-between md:items-center">
          <div class="flex items-center justify-between">
            <div>
              <a class="inline-block" href="/">
                <img src={Routes.static_path(@conn, "/images/phoenix.png")} class="object-contain h-8" />
              </a>
            </div>
          </div>

          <div class="flex items-center">
            <div class="flex flex-col md:flex-row md:mx-6">
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "my-1 text-sm text-gray-700 font-medium hover:text-indigo-500 md:mx-4 md:my-0" %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <%= @inner_content %>

    <footer class="py-3 mt-auto bg-gray-700">
      <div class="container max-w-4xl pb-4 mx-auto text-sm text-center text-gray-300">
        &copy; <%= DateTime.utc_now.year %> Cookie Cutters
      </div>
    </footer>
  </body>
</html>